apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/config.yaml
- namespace.yaml
secretGenerator:
- files:
  - jwtRS256.key
  - jwtRS256.key.pub
  name: jwt-key
  type: Opaque
