apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../resources

patchesJson6902:
- path: frontend-vs-patch.yaml
  target:
    group: networking.istio.io
    kind: VirtualService
    name: frontend
    version: v1alpha3
- path: frontend-gateway-patch.yaml
  target:
    group: networking.istio.io
    kind: Gateway
    name: frontend-gateway
    version: v1alpha3
- path: frontend-ingress-vs-patch.yaml
  target:
    group: networking.istio.io
    kind: VirtualService
    name: frontend-ingress
    version: v1alpha3
namespace: hipster
