apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/balance-reader.yaml
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/frontend.yaml
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/ledger-db.yaml
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/ledger-writer.yaml
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/loadgenerator.yaml
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/transaction-history.yaml
- ../../resources
- contacts-service.yaml
- contacts-se.yaml
- contacts-vs.yaml
- frontend-gateway.yaml
- frontend-vs.yaml
- userservice-service.yaml
- userservice-se.yaml
- userservice-vs.yaml
patchesJson6902:
- target:
    version: v1
    kind: Service
    name: frontend
  path: frontend-service-patch.yaml
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: ServiceEntry
    name: userservice-boa
  path: serviceentry-patch.yaml
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: ServiceEntry
    name: contacts-boa
  path: serviceentry-patch.yaml
namespace: boa
