apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# additional resources like ingress rules, cluster and repository secrets.
#- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.5.4
resources:
- argocd-namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v1.5.6
- projects/
- apps/
- argocd-server-vs.yaml
- argocd-gateway.yaml

namespace: argocd
images:
- name: argoproj/argocd
  newTag: v1.5.6
