---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-host
  label:
    name: update-host
spec:
  workspaces:
  - name: shared-workspace
  resources:
    inputs:
    - name: repo
      type: git
  params:
  - name: virtualservice-host
    type: string
  - name: gateway-host
    type: string
  - name: app
    type: string
  steps:
  - name: update-gateway
    image: golang:1.14.4-alpine
    command:
    - sed
    args:
    - -i
    - "s/*/$(inputs.params.gateway-host)/"
    - /workspace/repo/apps/$(inputs.params.app)/overlays/gcp/$(inputs.params.app)-gateway-patch.yaml
  - name: update-virtualservice
    image: golang:1.14.4-alpine
    command:
    - sed
    args:
    - -i
    - "s/*/$(inputs.params.virtualservice-host)/"
    - /workspace/repo/apps/$(inputs.params.app)/overlays/gcp/$(inputs.params.app)-vs-patch.yaml
  - name: copy-to-shared-space
    image: golang:1.14.4-alpine
    command:
    - cp
    args:
    - -R
    - /workspace/repo/apps/$(inputs.params.app) 
    - $(workspaces.shared-workspace.path)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hydrate-manifest
  label:
    name: hydrate-manifest
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: app
    type: string
  - name: env
    type: string
  steps:
  - name: hydrate
    image: gcr.io/kenthua-sharing/kustomize
    script: |
      #!/usr/bin/env sh
      set -euxo pipefail
      cd $(workspaces.shared-workspace.path)/$(inputs.params.app)/overlays/$(inputs.params.env)
      kustomize build > $(workspaces.shared-workspace.path)/$(inputs.params.env).yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push
  label:
    name: push
spec:
  workspaces:
  - name: shared-workspace
  resources:
    inputs:
    - name: repo-env
      type: git
  params:
  - name: app
    type: string
  - name: git-user-name
    type: string
  - name: git-user-email
    type: string
  - name: git-branch
    type: string
  - name: env
    type: string
  steps:
  - name: create-path
    image: gcr.io/kenthua-sharing/kustomize
    script: |
      #!/usr/bin/env sh
      set -euxo pipefail
      mkdir -p /workspace/repo-env/apps/$(inputs.params.app)/$(inputs.params.env)
  - name: copy-to-repo
    image: golang:1.14.4-alpine
    command:
    - cp
    args:
    - -R
    - $(workspaces.shared-workspace.path)/$(inputs.params.env).yaml
    - /workspace/repo-env/apps/$(inputs.params.app)/$(inputs.params.env)
  - name: push
    image: gcr.io/cloud-builders/git
    script: |
      #!/usr/bin/env bash
      set -euxo pipefail
      ln -s /tekton/home/.ssh /root/.ssh
      cd /workspace/repo-env
      git config user.email "$(inputs.params.git-user-email)"
      git config user.name "$(inputs.params.git-user-name)"
      git checkout -b $(inputs.params.git-branch)
      git add /workspace/repo-env/apps/$(inputs.params.app)/$(inputs.params.env)/$(inputs.params.env).yaml
      git commit -m 'tekton pipeline'
      git push origin $(inputs.params.git-branch) --force
---