---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-pipeline-resource
spec:
  type: git
  params:
    - name: url
      value: git@github.com:kenthua/anthos-cd-pipeline
    - name: revision
      value: master
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-host
spec:
  resources:
    inputs:
    - name: repo
      type: git
  params:
  - name: virtualservice-host
    type: string
  - name: gateway-host
    type: string
  - name: app
    type: string
  - name: git-user-name
    type: string
  - name: git-user-email
    type: string
  steps:
  - name: show-repo-clone
    image: golang:1.14-alpine
    workingDir: /workspace/repo/src
    command:
    - cat
    args:
    - /workspace/repo/README.md
  - name: update-gateway
    image: golang:1.14-alpine
    command:
    - sed
    args:
    - -i
    - "s/*/$(inputs.params.gateway-host)/"
    - /workspace/repo/apps/$(inputs.params.app)/overlays/gcp/$(inputs.params.app)-gateway-patch.yaml
  - name: update-virtualservice
    image: golang:1.14-alpine
    command:
    - sed
    args:
    - -i
    - "s/*/$(inputs.params.virtualservice-host)/"
    - /workspace/repo/apps/$(inputs.params.app)/overlays/gcp/$(inputs.params.app)-vs-patch.yaml
  - name: show
    image: golang:1.14-alpine
    command:
    - cat
    args:
    - /workspace/repo/apps/$(inputs.params.app)/overlays/gcp/$(inputs.params.app)-gateway-patch.yaml
  - name: push
    image: gcr.io/cloud-builders/git
    script: |
      #!/usr/bin/env bash
      set -euxo pipefail
      ln -s /tekton/home/.ssh /root/.ssh
      cd /workspace/repo
      git config user.email "$(inputs.params.git-user-email)"
      git config user.name "$(inputs.params.git-user-name)"
      git checkout -b gcp
      git add /workspace/repo/apps/$(inputs.params.app)/overlays/gcp/*.yaml
      git commit -m 'tekton pipeline'
      git push origin gcp --force
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: modify-resource
  labels:
    name: modify-resource
spec:
  serviceAccountName: robot-git-ssh
  taskRef:
    name: update-host
  params:
  - name: gateway-host
    value: "*.apps.standalone.kenthua.joonix.net"
  - name: virtualservice-host
    value: "bookinfo.apps.standalone.kenthua.joonix.net"
  - name: app
    value: bookinfo
  - name: git-user-name
    value: "name here"
  - name: git-user-email
    value: "email here"
  resources:
    inputs:
    - name: repo
      resourceRef:
        name: git-pipeline-resource
