apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: change-hydrate-push
spec:
  resources:
  - name: repo
    type: git
  - name: repo-env
    type: git
  params:
  - name: app
    type: string
  - name: git-user-name
    type: string
  - name: git-user-email
    type: string
  - name: git-branch
    type: string
  - name: env
    type: string
  - name: virtualservice-host
    type: string
  - name: gateway-host
    type: string     
  workspaces:
  - name: shared-workspace
  tasks:
  - name: update-host-task
    taskRef:
      name: update-host
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
    resources:
      inputs:
      - name: repo
        resource: repo
    params:        
    - name: virtualservice-host
      value: $(params.virtualservice-host)
    - name: gateway-host
      value: $(params.gateway-host)
    - name: app        
      value: $(params.app)
  - name: hydrate-manifest-task
    taskRef:
      name: hydrate-manifest
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
    params:        
    - name: app
      value: $(params.app)
    - name: env      
      value: $(params.env)
    runAfter:
      - update-host-task
  - name: push-task
    taskRef:
      name: push
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
    resources:
      inputs:
      - name: repo-env
        resource: repo-env
    params:
    - name: app
      value: $(params.app)
    - name: git-user-name
      value: $(params.git-user-name)
    - name: git-user-email
      value: $(params.git-user-email)    
    - name: git-branch
      value: $(params.git-branch)    
    - name: env
      value: $(params.env)    
    runAfter:
      - hydrate-manifest-task
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
#  generateName: change-hydrate-push-
  name: change-hydrate-push
spec:
  serviceAccountNames:
  - taskName: update-host-task
    serviceAccountName: robot-git-ssh
  - taskName: push-task
    serviceAccountName: robot-git-env-ssh
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: shared-task-storage
  pipelineRef:
    name: change-hydrate-push
  params:
  - name: gateway-host
    value: "*.apps.standalone.kenthua.joonix.net"
  - name: virtualservice-host
    value: "bookinfo.apps.standalone.kenthua.joonix.net"
  - name: app
    value: bookinfo
  - name: git-user-name
    value: "name here"
  - name: git-user-email
    value: "email here"
  - name: git-branch
    value: main
  - name: env
    value: gcp
  resources:
  - name: repo
    resourceRef:
      name: git-pipeline-resource
  - name: repo-env
    resourceRef:
      name: git-pipeline-env-resource