apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../resources
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/accounts-db.yaml
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/contacts.yaml
- https://raw.githubusercontent.com/GoogleCloudPlatform/bank-of-anthos/master/kubernetes-manifests/userservice.yaml
namespace: boa
