apiVersion: v1
data:
  admin.password: JDJ5JDEwJDd4QkpPdDBmRnd1dzNLN0tBV3ZQTk9MeUhoLm5iaGxUekcvYlY1Q3o1djhBbHIvWlY2YzZT
  admin.passwordMtime: MjAyMC0wMy0yMVQxNTozNToxOVo=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
