apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service
            - --k8s-secret-name=git-creds
            - --git-branch=gcp
            - --git-path=apps/bookinfo/overlays/gcp
            - --git-url=git@github.com:kenthua/anthos-cd-pipeline
