apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-platform
spec:
  project: infra
  source:
    repoURL: 'https://github.com/kenthua/anthos-cd-pipeline'
    path: infra/argocd/overlays/gcp
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
