apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipster
spec:
  project: default
  source:
    repoURL: 'https://github.com/kenthua/anthos-cd-pipeline'
    path: apps/hipster/overlays/gcp
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  ignoreDifferences:
  - kind: Namespace
    version: v1
    jsonPointers:
    - /metadata/annotations
    - /metadata/labels
  syncPolicy:
    automated:
      selfHeal: true
