apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
spec:
  project: default
  source:
    repoURL: 'https://github.com/kenthua/anthos-cd-pipeline'
    path: apps/bookinfo/overlays/gcp
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  # syncPolicy:
  #   automated:
  #     selfHeal: true
