apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bookinfo-namespace.yaml
- https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/platform/kube/bookinfo.yaml
- https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/networking/bookinfo-gateway.yaml
- https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/networking/destination-rule-all-mtls.yaml

